- hosts: master

  tasks:
    - name: copy .conf files to apache config
      copy:
        src: files/{{ item }}.conf
        dest: /etc/httpd/conf.d/{{ item }}.conf
        backup: yes
      with_items:
        - userportal
        - bright-view
        - openstack

    - name: fix application paths in bright cluster web landing page
      replace:
         path: /var/www/html/index.php
         regexp: '{{ item.regexp }}'
         replace: '{{ item.replace }}'
         backup: yes
      with_items:
          - { regexp: ":8081/userportal", replace: "/userportal" }
          - { regexp: ":8081/bright-view", replace: "/bright-view" }
          - { regexp: ":10080/", replace: "/openstack" }

    - name: Restart service httpd, in all cases
      service:
        name: httpd
        state: restarted

# implment https listener for openstack
# http://kb.brightcomputing.com/faq/index.php?action=artikel&cat=24&id=416
    - name: add shorewall rules for ssl openstack
      lineinfile:
        path: /etc/shorewall/rules
        regexp: '^ACCEPT.*10081.*'
        insertafter: '10080'
        line: 'ACCEPT   net            fw              tcp     10081 # OpenStack Horizon (ssl)'
        backup: yes

    - name: add shorewall rules for ssl novnc console
      lineinfile:
        path: /etc/shorewall/rules
        regexp: '^ACCEPT.*6081.*'
        insertafter: '6080'
        line: 'ACCEPT   net            fw              tcp     6081 # OpenStack  NoVNCProxy (ssl)'
        backup: yes

    - name: restart shorewall
      shell: /cm/local/apps/cmd/bin/cmsh -c "device use master; services; restart shorewall"

    - name: put haproxy cert bundle in replace
      copy:
        src: /root/cert-bundle.pem
        dest: /etc/haproxy/cert-bundle.pem
        remote_src: yes

    - name: add haproxy rules for ssl horizon and novnc console
      blockinfile:
        path: /etc/haproxy/haproxy.cfg
        insertafter: '^# END AUTOGENERATED SECTION'
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        backup: yes
        block: |
          listen dashboard-horizon-https
            mode http
            bind 0.0.0.0:10081 ssl crt /etc/haproxy/cert-bundle.pem
            reqadd X-Forwarded-Proto:\ https
            server auto-n01::192.168.17.1:80 192.168.17.1:80 check

          listen VNC-https
            mode http
            bind 0.0.0.0:6081 ssl crt /etc/haproxy/cert-bundle.pem
            server auto-n01::192.168.17.1:16080 192.168.17.1:16080 check

    - name: restart haproxy
      shell: /cm/local/apps/cmd/bin/cmsh -c "device use master; services; restart haproxy"

    - name: add novnc proxy to cluster config
      shell: /cm/local/apps/cmd/bin/cmsh -c "configurationoverlay; use openstackhypervisors; customizations; add /etc/nova/nova.conf; entries; add vnc novncproxy_base_url=https://ruffner.rc.uab.edu:6081/vnc_auto.html; commit"
