- hosts: master

  tasks:
    - name: copy .conf files to apache config
      copy:
        src: files/{{ item }}.conf
        dest: /etc/httpd/conf.d/{{ item }}.conf
        backup: yes
      with_items:
        - userportal
        - bright-view
        - openstack

    - name: fix application paths in bright cluster web landing page
      replace:
         path: /var/www/html/index.php
         regexp: '{{ item.regexp }}'
         replace: '{{ item.replace }}'
         backup: yes
      with_items:
          - { regexp: ":8081/userportal", replace: "/userportal" }
          - { regexp: ":8081/bright-view", replace: "/bright-view" }
          - { regexp: ":10080/", replace: "/openstack" }

    - name: Restart service httpd, in all cases
      service:
        name: httpd
        state: restarted
